version: '2'
services:
  mysql_app:
     container_name: mysql_app
     image: mysql
     ports:
     - "3300:3306"
     volumes:
     - ./db_data_app:/var/lib/mysql
     environment:
     - MYSQL_ROOT_PASSWORD=root
  mysql1:
     container_name: mysql1
     image: mysql
     ports:
     - "3301:3306"
     volumes:
     - ./db_data1:/var/lib/mysql
     - ./mysql:/import
     environment:
     - MYSQL_ROOT_PASSWORD=root
  mysql2:
     container_name: mysql2
     image: mysql
     ports:
     - "3302:3306"
     volumes:
     - ./db_data2:/var/lib/mysql
     - ./mysql:/import
     environment:
     - MYSQL_ROOT_PASSWORD=root
  mysql3:
     container_name: mysql3
     image: mysql
     ports:
     - "3303:3306"
     volumes:
     - ./db_data3:/var/lib/mysql
     - ./mysql:/import
     environment:
     - MYSQL_ROOT_PASSWORD=root
